### ISSUE TITLE
refresh lazy-load

### ISSUE THREAD

**Issue by wahyupermadie** [mazipan/vue-tiny-lazyload-img#1]
sore, saya mau tanya bagaimana cara merefresh image lazy load nya ketika button yang di klik berubah ?
permasalahannya ketika saya klik button A datanya muncul sesuai button A, namun ketika klik button B dan yang lainnya image nya tidak muncul sesuai button yang saya pilih namun image yang muncul adalah image di button A.
ketika saya inspect element ternyata pada tag img src tetap mengacu pada url image A, sedangkan :data-src berubah sesuai image url masing2 button yang dipilih.

ini syntax di component saya
[https://pastebin.com/9fYes6GX](url)

ini hasil inspect element
[https://pastebin.com/9kC8wTb7](url)

**Comment by mazipan** [comment]
Update to 0.0.3 ya @wahyupermadie 
Don't forget to give ⭐️ in this repo 😗
