### ISSUE TITLE
Lazyload on Safari Issue

### ISSUE THREAD

**Issue by eertmanhidde** [mazipan/vue-tiny-lazyload-img#4]
The plugin works great in Chrome and Firefox but in Safari I get the following error ```TypeError: null is not an object (evaluating 'p.observe')```. 

The site works in Safari but it shows the low quality image: 
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/45388384/55626613-4a0f0300-57ac-11e9-8628-9f3ad67e106b.png">

Yes, I've used the polyfill you suggested in the documentation.

This is how the plugin looks: 
```
import Vue from 'vue';

import VueTinyLazyloadImg from 'vue-tiny-lazyload-img';

// Polyfill
import 'intersection-observer';

Vue.use(VueTinyLazyloadImg);
```

The <a target="blank" href="https://mazipan.github.io/vue-tiny-lazyload-img/">demo page</a> also doesn't work in Safari. Would be awesome if this would work :)

Safari version: 12.0.3

**Comment by mazipan** [comment]
This is because polyfill is not working as expected.

I change polyfill to [polyfill.io](https://cdn.polyfill.io/v2/docs/), which will automatically include dependencies where necessary:

```html
<script src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver"></script>
```

cc: @eertmanhidde
